title: Domčík ve Finsku
description: > # this means to ignore newlines until "baseurl:"
  Web o mém pobytu ve Finsku na Aaltově univerzitě, 2021/2022.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dominik Hodan # add your name
author-img: domcik_a_spot.png # add your photo
about-author: Vítejte na blogu o mém Erasmu ve Finsku na Aaltově univerzitě, 2021/2022.
              Příspěvky tu určitě nebudou přibývat pravidelně, ale podle toho, jestli se bude něco zajímavého dít.
              Když korona dá, tak tu i bude něco jiného než fotky pokoje. :-)
# social-twitter: # add your Twitter handle
social-facebook: dominik.hodan # add your Facebook handle
social-github: tragram # add your Github handle
# social-linkedin: # add your Linkedin handle
social-email: domho108@gmail.com # add your Email address

# Disqus
discus-identifier: domczik # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
